- hosts: front
  become: yes
  tasks:
  
    - name: Install pkg
      apt:
        pkg:
          - curl
          - git
          - gpg
        state: latest
        update_cache: yes

    - name: "Add nodejs apt key"
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: "Add nodejs 14.x ppa for apt repo"
      apt_repository:
        repo: deb https://deb.nodesource.com/node_14.x bionic main
        update_cache: yes

    - name: "Install nodejs"
      apt:
        update_cache: yes
        name: nodejs
        state: present

    - name: Example clone of a single branch
      ansible.builtin.git:
        repo: https://github.com/KoM-Kind-of-Magic/KoM-Website
        dest: code
        single_branch: yes
        version: devops
    
    - name: Install pm2
      shell: npm install -g pm2   

    - name: Install node modules
      shell: cd code && sudo npm install

    - name: Launch server
      shell: cd code && pm2 start "npm run start"